### ISSUE TITLE
 user-stroies

### ISSUE THREAD

**Issue by gelilaa** [gelilaa/VoxBox#2]
please write your user stories under here.....

**Comment by gelilaa** [comment]
@mametur 
There are two ways to sign in=> As Admin and as User?
1. As a mobile (tablet||pc) user, I can sign-in or sign-up for the application so that I can help people or get some help. (name,lastName,NickName,email,city,country..)
2. As a user, I want to have a unique nickName to join the application so that I will have a more secure profile.
3. As a user, I want to make a post so that I can inform people that I need to help.
4. As a user, I want to change or delete my post so that I can be sure of the content of my post is accurate.
6. As a user, I can leave comments below to any post so that we can communicate with each other. 
7. As a user, I don't want anyone to be able to delete my post so that I can make sure my post is always there.
8. As a user, I want to sign-out from the application so that I can be sure that I am not online.

**Comment by adekimpianna** [comment]
8. As a user, I want people to be able to see my picture, so that people can see me and trust me. 
9. As a user, I want to have a profile so where I can explain about my self and people can know and trust me. 
10. As a user I want to see a list or a total number of volunteer activities I have completed so people can trust me better.
11. As a user I want to see a list of help I ask so I can track my help requests easily because I may need helps for two different things.
12. As a user I want to be able to be a volunteer but sometimes I may need some help to so that I can give not only take. ==> related to the question that @gelilaa asked to @mametur in above post (honestly, I think one way to sign in is better, no admin, everyone is a user/member of the volunteer community, so they can ask help and give help at the same time via this app)
13. As a user I want to see which helps that have agreed volunteers already and which ones are not so that I can easily search for helps that still need my help.

**Comment by oguzkarademir** [comment]
14. As a user, I want to be able to use my google or facebook account to sign up

15. As a user, I want to be able to list, filter and sort all help requests by proximity after logging in.

**Comment by yildiraykoyuncu** [comment]
16. As a user I want to be able to mark a help request I made as solved, so people would know that I no longer need help for that issue.

17. As a user I want to be able to give likes or stars to the volunteers who helped me, which may motivate volunteers to be more eager to help.

18. As a user I want to be able to upload photos about my problem to be able better explain it

19. As a user I want to see a list of the most active volunteers

20. As a user I want to be able to organize help events, to help people who do not have access to the internet or do not know how to use it (for elders mostly), or form teams for tasks that need more than one people.

21. As a user I want to be able to see upcoming help events and info about the event (where and when, to whom, what kind of tools or expertise they need, etc.)

**Comment by miroslavveljanoski** [comment]
22. As a user, I want to leave comment or review for the volunteer that helped me, so that can be useful for other users in the future. 

23. As a user, I want to leave a post with a help request with details about the problem, location, contact details, so the volunteers can comment and offer their knowledge and availability.

24. As a user, I want to be able to share my post on Facebook, so more people can see my request.

Most of the other ideas are already written by my teammates 😄 

I have two ideas about this app. 
The __first one__ is to look like Facebook. Users can make post with specific details, for example I have some problem with the water system in my bathroom, is there someone available that can help. I live
in Gent. The people can comment on this post, and from there they can exchange more details between each other and 
agree how to fix the problem.
The __second idea__ is this app to have categories, so the volunteers when they are signing up can pick up a category in which they can offer help, for example electricity, water system, cars, gardens...The users who need help can search volunteers per category, pick some of them and contact him/her by phone and ask for help

**Comment by LujiAnna** [comment]
25. As a user, I should be able to arrive at the landing page so that I can get an overview of the app

**Comment by LujiAnna** [comment]
26. As a user I should see a link with an option to recover a lost password incase I forgot my password

**Comment by gelilaa** [comment]
> 
> 
> @mametur
> There are two ways to sign in=> As Admin and as User?
> user login is a must
> admin nice to  have

>     1. As a mobile (tablet||pc) user, I can sign-in or sign-up for the application so that I can help people or get some help. (name,lastName,NickName,email,city,country..(picture))
>  must 
>     2. As a user, I want to have a unique nickName to join the application so that I will have a more secure profile.
> not suggested to have ( must be real name)
>     3. As a user, I want to make a post so that I can inform people that I need to help.
> card must 
>     4. As a user, I want to change or delete my post so that I can be sure of the content of my post is accurate.
> must 
>     5. As a user, I can leave comments below to any post so that we can communicate with each other.
> must 
>     6. As a user, I don't want anyone to be able to delete and change my post so that I can make sure my post is always there.
> must 
>     7. As a user, I want to sign-out from the application so that I can be sure that I am not online.
>must

**Comment by oguzkarademir** [comment]
27. As a user, I want to be able to write feedback and give points between 1-5 stars to the volunteer who helped me.

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user, I want people to be able to see my picture, so that people can see me and trust me.
>   nice to have (when you sign-up you will be provided with avatars)
>     2. As a user, I want to have a profile so where I can explain about my self and people can know and trust me.
>  profile ....( tell us about your self) must
>     3. As a user I want to see a list or a total number of volunteer activities I have completed so people can trust me better.
>  nice to have
>     4. As a user I want to see a list of help I ask so I can track my help requests easily because I may need helps for two different things.
>  could have
>     5. As a user I want to be able to be a volunteer but sometimes I may need some help to so that I can give not only take. ==> related to the question that @gelilaa asked to @mametur in above post (honestly, I think one way to sign in is better, no admin, everyone is a user/member of the volunteer community, so they can ask help and give help at the same time via this app)
> 
>     6. As a user I want to see which helps that have agreed volunteers already and which ones are not so that I can easily search for helps that still need my help.
a solved button for a card which only be accessed by the user who post the card...(nice to have)

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user, I want to be able to use my google or facebook account to sign up
>  nice to have 
> 
>     2. As a user, I want to be able to list, filter and sort all help requests by proximity(Geo-location) after logging in.

>  nice to have ....

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user I want to be able to mark a help request I made as solved, so people would know that I no longer need help for that issue.
>  already been discussed as nice to have
>     2. As a user I want to be able to give likes or stars to the volunteers who helped me, which may motivate volunteers to be more eager to help.
> must have

>     3. As a user I want to be able to upload photos about my problem to be able better explain it
>  already been discussed as nice to have
>     4. As a user I want to see a list of the most active volunteers
>  nice to have
>     5. As a user I want to be able to organize help events, to help people who do not have access to the internet or do not know how to use it (for elders mostly), or form teams for tasks that need more than one people.
> to create a Group ....nice to have 
>     6. As a user I want to be able to see upcoming help events and info about the event (where and when, to whom, what kind of tools or expertise they need, etc.)
> nice to have

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user, I want to leave comment or review for the volunteer that helped me, so that can be useful for other users in the future.
>   reviews ....already been discussed as nice to have 
>     2. As a user, I want to leave a post with a help request with details about the problem, location, contact details, so the volunteers can comment and offer their knowledge and availability.
> .....cards ...already been discussed an must have
>     3. As a user, I want to be able to share my post on Facebook, so more people can see my request.
>  could have 
> 
> Most of the other ideas are already written by my teammates 😄
> 
discussed already ....
> I have two ideas about this app.
> The **first one** is to look like Facebook. Users can make post with specific details, for example I have some problem with the water system in my bathroom, is there someone available that can help. I live
> in Gent. The people can comment on this post, and from there they can exchange more details between each other and
> agree how to fix the problem.
> The **second idea** is this app to have categories, so the volunteers when they are signing up can pick up a category in which they can offer help, for example electricity, water system, cars, gardens...The users who need help can search volunteers per category, pick some of them and contact him/her by phone and ask for help

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user, I should be able to arrive at the landing page so that I can get an overview of the app

> landing page is a must have

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user, I should be able to arrive at the landing page so that I can get an overview of the app

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user I should see a link with an option to recover a lost password incase I forgot my password

oguz will do it - must have

**Comment by gelilaa** [comment]
> 
> 
>     1. As a user, I want to be able to write feedback and give points between 1-5 stars to the volunteer who helped me.

discussed already...reviews
